name=NTCTemp
version=1.0.0
author=Abdul Rafeul Mallick
maintainer=Abdul Rafeul Mallick
sentence=Universal NTC thermistor temperature library for microcontrollers.
paragraph=Simple and lightweight NTC thermistor library for Arduino, ESP32, ESP8266, Raspberry Pi Pico, STM32 and other compatible microcontrollers. Supports Celsius and Fahrenheit readings with customizable beta coefficient, nominal temperature and ADC resolution.
category=Sensors
url=https://github.com/Rafeul1997/NTCTemp
architectures=*
